name: Build

on:
  push:

defaults:
  run:
    shell: bash -euxo pipefail

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo 'hello'
          pwd
          env | sort
