name: Build

on:
  push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug
        run: |
          echo ${{ github.event.repository.name }}
          echo '----'
          echo ${GITHUB_REPOSITORY#*/}
          
      - name: Test GITHUB_SHA
        shell: bash
        run: |
          echo $GITHUB_SHA


