name: Deploy

on:
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

  workflow_dispatch:
    inputs:
      foo:
        description: 'This is required foo'
        default: 'I am foo!'
        required: true
      bar:
        description: 'This is an optional bar'
        required: false

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: echo 'Deploy!'
