name: Deploy

on:
  release:

  workflow_dispatch:
    inputs:
      foo:
        description: 'This is required foo'
        default: 'I am foo!'
        required: true
      bar:
        description: 'This is an optional bar'
        required: false

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' ||  github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: echo 'Deploy!'

      - name: Foo
        run: echo "Hello ${{ github.event.inputs.foo }}"

      - name: Bar
        run: echo "Hello ${{ github.event.inputs.bar }}"
