# This is a basic workflow that is manually triggered.

name: Manual workflow
  
on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'This is required foo'
        default: 'I am foo!'
        required: true
      bar:
        description: 'This is an optional bar'
        required: false

jobs:
  greet:
    runs-on: self-hosted
    steps:
    - name: Foo
      run: echo "Hello ${{ github.event.inputs.foo }}"
    - name: Bar
      run: echo "Hello ${{ github.event.inputs.bar }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        push: false
        tags: vterdunov/github-action:latest
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
   
    - name: Docker image ls
      run: docker image ls
    - name: Docker inspect
      run: docker image inspect vterdunov/github-action
