# This is a basic workflow that is manually triggered

name: Manual workflow
  
on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'This is required foo'
        default: 'I am foo!'
        required: true
      bar:
        description: 'This is an optional bar'
        required: false

jobs:
  greet:
    runs-on: self-hosted
    steps:
    - name: Inputs
      run: echo "Hello ${{ github.event.inputs.foo }}"
    - run: echo "Hello ${{ github.event.inputs.bar }}"
    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - run: java -cp java HelloWorldApp
