# This is a basic workflow that is manually triggered.

name: Manual workflow
  
on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'This is required foo'
        default: 'I am foo!'
        required: true
      bar:
        description: 'This is an optional bar'
        required: false

jobs:
  greet:
    runs-on: self-hosted
    steps:
    - name: Foo
      run: echo "Hello ${{ github.event.inputs.foo }}"
    - name: Bar
      run: echo "Hello ${{ github.event.inputs.bar }}"

    - name: Print input
      run: |
        echo "FOO is: $INPUT_FOO"
        echo "BAR is: $INPUT_BAR"
