# This is a basic workflow that is manually triggered

name: Manual workflow
  
on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'This is required foo'
        default: 'I am foo!'
        required: true
      bar:
        description: 'This is an optional bar'
        required: false

jobs:
  greet:
    runs-on: self-hosted
    steps:
    - name: Inputs
      run: echo "Hello ${{ github.event.inputs.foo }}"
    - run: echo "Hello ${{ github.event.inputs.bar }}"
