name: Rebase

on:
  pull_request:
    types:
      - opened
  issue_comment:
    types:
      - created

jobs:
  rebase:
    if: contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
