name: Get tag

on:
  push:
    tags: 
      - "*"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        run: echo ${GITHUB_REF#refs/tags/}
